logging:
  level:
    root: warn
    tk.mybatis.springboot.mapper: trace
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: xuechaoke
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
